# Generated by Django 5.1.2 on 2024-11-28 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.contrib.gis.db import models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('N', 'Neighborhood'), ('CT', 'City'), ('S', 'State'), ('C', 'Country')], default='N', max_length=2)),
                ('geometry', django.contrib.gis.db.models.PolygonField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('square_meters', models.FloatField()),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('link', models.CharField(max_length=100)),
                ('listing_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('C', 'Casa'), ('A', 'Apartamento'), ('T', 'Terreno')], max_length=1)),
                ('coordinates', django.contrib.gis.db.models.PointField(geography=True, null=True, srid=4326)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate_lens.location')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
