# Generated by Django 5.1.2 on 2024-11-28 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_lens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
