# Generated by Django 5.1.2 on 2024-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_lens', '0002_alter_location_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='link',
            field=models.CharField(),
        ),
    ]
