# Generated by Django 5.1.2 on 2024-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_lens', '0003_alter_property_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_date',
            field=models.DateField(null=True),
        ),
    ]
