# Generated by Django 5.1.2 on 2024-11-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_lens', '0004_alter_property_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='real_estate_lens.location'),
        ),
    ]
