# Generated by Django 5.1.2 on 2025-05-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_lens', '0006_location_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_links', to='real_estate_lens.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_locations_links', to='real_estate_lens.user')),
            ],
            options={
                'db_table': 'user_favorite_locations',
                'ordering': ['-favorited_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_locations',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', through='real_estate_lens.FavoriteLocation', to='real_estate_lens.location'),
        ),
        migrations.AddConstraint(
            model_name='favoritelocation',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='uniq_user_favorite_location'),
        ),
    ]
